# Generated by Django 3.2.7 on 2021-11-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='Pic',
        ),
    ]
