# Generated by Django 3.2.7 on 2021-11-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pic_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='Pic',
        ),
    ]
