# Generated by Django 3.2.7 on 2021-11-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_pic_product_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Pic',
            new_name='pic',
        ),
    ]
