# Generated by Django 3.2.7 on 2021-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='products'),
        ),
    ]
