# Generated by Django 3.2.7 on 2021-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_buy_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buy_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
