# Generated by Django 3.2.7 on 2021-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_buy_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
