# Generated by Django 3.2.7 on 2021-12-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211208_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='expected_del',
            new_name='expected_date',
        ),
    ]
